const taskListTypes = {
  // CREATE
  CREATE_NEW_TASK: 'CREATE_NEW_TASK',
  // READ
  READ_ALL_STATE: 'READ_ALL_STATE',
  READ_TASK_LIST: 'READ_TASK_LIST',
  READ_FILTER_FIELD: 'READ_FILTER_FIELD',
  // UPDATE
  UPDATE_TASK_LIST_ITEM: 'UPDATE_TASK_LIST_ITEM',
  UPDATE_FILTER_SEARCH: 'UPDATE_FILTER_SEARCH',
  UPDATE_FILTER_ASC: 'UPDATE_FILTER_ASC',
  UPDATE_FILTER_DETAIL: 'UPDATE_FILTER_DETAIL',
  // DELETE
  DELETE_ALL_STATE: 'DELETE_ALL_STATE',
  DELETE_TASK: 'DELETE_TASK',
};

export default taskListTypes;
